import type { Connector } from "@/lib/mock/types"

export const connectorCatalog: Connector[] = [
  {
    id: "ds_postgres",
    provider: "postgres",
    name: "PostgreSQL (Neon, serveur, RDS…) à connecter",
    status: "not_connected",
    syncMode: "scheduled",
    lastSyncAt: null,
    nextSyncAt: null,
    lastError: null,
    recordsSynced: 0,
    permissions: [
      "Lecture seule des tables (rôle SELECT only recommandé)",
      "Chaîne de connexion stockée chiffrée côté serveur",
      "Aucune écriture dans la base analysée",
    ],
  },
  {
    id: "ds_supabase",
    provider: "supabase_postgres",
    name: "Supabase / Postgres à connecter",
    status: "not_connected",
    syncMode: "scheduled",
    lastSyncAt: null,
    nextSyncAt: null,
    lastError: null,
    recordsSynced: 0,
    permissions: [
      "Lecture seule des tables Supabase",
      "Chaîne de connexion stockée chiffrée côté serveur",
      "Aucune écriture dans la base analysée",
    ],
  },
  {
    id: "ds_firebase",
    provider: "firebase_firestore",
    name: "Firebase / Firestore à connecter",
    status: "not_connected",
    syncMode: "scheduled",
    lastSyncAt: null,
    nextSyncAt: null,
    lastError: null,
    recordsSynced: 0,
    permissions: [
      "Lecture seule des collections Firebase",
      "Service account stocké chiffré côté serveur",
      "Aucune écriture dans l'application analysée",
    ],
  },
  {
    id: "ds_rest",
    provider: "rest_api",
    name: "Endpoint REST à connecter",
    status: "not_connected",
    syncMode: "scheduled",
    lastSyncAt: null,
    nextSyncAt: null,
    lastError: null,
    recordsSynced: 0,
    permissions: [
      "Lecture seule via l'endpoint fourni",
      "Token d'accès stocké chiffré côté serveur",
      "Aucune écriture vers l'API analysée",
    ],
  },
  {
    id: "ds_webhook",
    provider: "webhook_events",
    name: "Webhook / collecteur à connecter",
    status: "not_connected",
    syncMode: "incremental",
    lastSyncAt: null,
    nextSyncAt: null,
    lastError: null,
    recordsSynced: 0,
    permissions: [
      "Réception d'événements en lecture seule",
      "Clé de signature stockée chiffrée côté serveur",
      "Aucune écriture vers la source émettrice",
    ],
  },
  {
    id: "ds_stripe",
    provider: "stripe_readonly",
    name: "Stripe (lecture seule) à connecter",
    status: "not_connected",
    syncMode: "scheduled",
    lastSyncAt: null,
    nextSyncAt: null,
    lastError: null,
    recordsSynced: 0,
    permissions: [
      "Lecture seule des paiements et abonnements",
      "Clé restreinte (restricted key) stockée chiffrée côté serveur",
      "Aucune modification des données Stripe",
    ],
  },
]
